# Example configuration for API deceit

# First deceit
[[deceit]]
uri = "/api/endpoint"

code = 200

matchers = [
    { type = "method", eq = "POST" },
    { type = "header", key = "Content-Type", value = "application/json" },
]

headers = [["Content-Type", "application/json"]]

json_request = true

[[deceit.processors]]
type = "lua"
scope = "pre"
script = """
-- This is some Lua script here
"""

[[deceit.responses]]
matchers = []
headers = []
processors = []
content = """
Template multiline
"""

[[deceit.responses.processors]]
type = "lua"
scope = "post"
script = """
-- This is some Lua script here
"""

